config/routes.rb
Rails.application.routes.draw do
  get 'search',to:'evnts#search'
  get 'event',to:'evnts#event'
  post 'event',to:'evnts#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get 'home',to: 'static_pages#home'
  root 'static_pages#home'
  get 'register',to: 'users#register'
  get 'htmlQuiz',to: 'static_pages#htmlQuiz'
  get 'gkQuiz',to: 'static_pages#gkQuiz'
  get 'mathQuiz',to: 'static_pages#mathQuiz'
  get 'englishQuiz',to: 'static_pages#englishQuiz'
  resources :users
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evnt.rb
class Evnt < ApplicationRecord
  	validates :title, presence: true ,length: {maximum: 50}
end

app/models/user.rb
class User < ApplicationRecord

	VALID_REGEX_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence: true ,length: {maximum: 50}
	validates :email, presence: true , length: {maximum: 255},
						format: {with: VALID_REGEX_EMAIL},
						uniqueness: {case_sensitive: false}
	validates :phone_number, presence: true, length: {minimum: 10,maximum:10}
	validates :password, presence: true, length: {minimum: 6}
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

app/controllers/evnts_controller.rb
class EvntsController < ApplicationController
  def search
  end

  def event
    @event = Evnt.new
  end
  def create
    @event =Evnt.new(cart_params)
    if @event.save
      redirect_to '#home'
    else
      render 'event'
    end
    end
    def cart_params
      params.require(:event).permit(:title)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user_email =params[:session][:email]
  	user =User.find_by(email: user_email)
  	if user && user.authenticate(params[:session][:password])
      log_in user
  		redirect_to '#about'
  	else
  		flash[:danger]="Email or Password Incorrect."
  		render 'new'
  	end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def mathQuiz
  end

  def engishquiz
  end

  def gkQuiz
  end

  def htmlQuiz
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def register
		@user=User.new
	end

	def show
  	end

	def create
  	@user =User.new(user_params)
  	if @user.save
      log_in @user
  		redirect_to '#about'
  	else
  		render 'register'
  	end
  	end

  	private
   	def user_params
   		params.require(:user).permit(:name, :email , :phone_number,:password, :password_confirmation)
   	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/evnts_helper.rb
module EvntsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def current_user
		if session[:user_id]
			@current_user=@current_user || User.find_by(id: session[:user_id])
		end
	end

	def logged_in?
		return !current_user.nil?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/evnts/event.html.erb
<h1>Evnts#event</h1>

	<div class="container">
		<h1>Register for Event</h1>
		<div class="row">
			<div class="col-md-2">
				<%= form_with(model: @event , local: true) do |f| %>
				<%= f.label :Title %>
				<%= f.text_field :title %>
				<%= f.submit "Register" , class: "btn btn-primary" %>
				<% end %>
			</div>
		</div>
	</div>

app/views/evnts/search.html.erb
<h1>Evnts#search</h1>
<p>Find me in app/views/evnts/search.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top" style="font-size:32px;">Event Website</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto my-2 my-lg-0">
                <li class="nav-item"><a class="nav-link js-scroll-trigger btn" href="#about" style="margin-top:10px; font-size:18px;" id="btn">About</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger btn" href="#event" style="margin-top:10px; font-size:18px;" id="btn">Event</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger btn" href="#contact" style="margin-top:10px; font-size:18px;" id="btn">Contact</a></li>
                <% if logged_in? %>
                      <li class="nav-item">
                        <div class="nav-link">
                        <%= link_to 'Logout', logout_path ,class:"btn btn-warning"%>
                      </li>
                  <% else %>
                      <li class="nav-item">
                        <div class="nav-link">
                        <%= link_to 'Login', login_path ,class:"btn btn-warning"%>
                      </li>
                      <li class="nav-item">
                        <div class="nav-link">
                        <%= link_to 'Sign up', register_path ,class:"btn btn-warning"%>
                      </li>
                  <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
       <!-- Font Awesome icons (free version)-->
       <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
       <!-- Google fonts-->
       <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
       <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
       <!-- Third party plugin CSS-->
       <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />

       <!-- Core theme CSS (includes Bootstrap)-->
       <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
       <link href="app/assets/stylesheet/styles.css" rel="stylesheet" />
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <div class="container" id="msg">
      <div class="msg">
      <%flash.each do |message_type , message| %>
      <div class="alert alert-<%= message_type%>">
        <%= message %>
      </div>
      <% end %>
        </div>
        </div>
    <%= yield %>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>

      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>

      <script src="app/javascript/scripts.js"></script>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div>
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, 
			"error" ) %>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
			<li> <%= msg %>></li>
			<% end %>
		</ul>
		</div>
	</div>
<% end %>

app/views/static_pages/englishQuiz.html.erb
<% if logged_in? %>
<div class="container-fluid ">
  <%=link_to 'Back' , 'home',class:"btn btn-secondary btn-lg"%>
</div>
    <div class="app-quiz">
    <%= javascript_pack_tag 'englishQuiz' %>
    </div>
    
<% else %>
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top" style="font-size:32px;">Event Website</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto my-2 my-lg-0">
                <% if logged_in? %>
                      <li class="nav-item">
                        <div class="nav-link">
                        <%= link_to 'Logout', logout_path ,class:"btn btn-warning"%>
                      </li>
                  <% else %>
                      <li class="nav-item">
                        <div class="nav-link">
                        <%= link_to 'Login', login_path ,class:"btn btn-warning"%>
                      </li>
                      <li class="nav-item">
                        <div class="nav-link">
                        <%= link_to 'Sign up', register_path ,class:"btn btn-warning"%>
                      </li>
                  <% end %>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid" id="error">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template" style="padding:150px 0 0 0;">
                <h1>
                    Oops!</h1>
                <h2>Seems You are not Logged-in</h2>
                <div class="error-details">
                    Sorry, an error has occured, Requested page not found!
                </div>
                <div class="error-actions">
                      	 <%= link_to 'Please Login' ,login_path ,class:"btn btn-primary btn-lg"%>
                         <%=link_to 'Back' , 'home',class:"btn btn-info btn-lg"%>
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="bg-light py-5">
    <div class="container"><div class="small text-center text-muted" style="color:#000;"> Copyright © 2020 - CodeQuest Internship Project</div></div>
</footer>

<% end %>

app/views/static_pages/gkQuiz.html.erb
<% if logged_in? %>
<div class="container-fluid" style="margin:0 0 50px 0;">
<%=link_to 'Back' , 'home',class:"btn btn-secondary btn-lg"%>
</div>
<div class="app-quiz">
<%= javascript_pack_tag 'gkQuiz' %>
</div>

<% else %>
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top" style="font-size:32px;">Event Website</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto my-2 my-lg-0">
                <% if logged_in? %>
                      <li class="nav-item">
                        <div class="nav-link">
                        <%= link_to 'Logout', logout_path ,class:"btn btn-warning"%>
                      </li>
                  <% else %>
                      <li class="nav-item">
                        <div class="nav-link">
                        <%= link_to 'Login', login_path ,class:"btn btn-warning"%>
                      </li>
                      <li class="nav-item">
                        <div class="nav-link">
                        <%= link_to 'Sign up', register_path ,class:"btn btn-warning"%>
                      </li>
                  <% end %>
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid" id="error">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template" style="padding:150px 0 0 0;">
                <h1>
                    Oops!</h1>
                <h2>Seems You are not Logged-in</h2>
                <div class="error-details">
                    Sorry, an error has occured, Requested page not found!
                </div>
                <div class="error-actions">
                  <span class="glyphicon glyphicon-home"></span>
                      	 <%= link_to 'Please Login' ,login_path ,class:"btn btn-primary btn-lg"%>
                         <%=link_to 'Back' , 'home',class:"btn btn-info btn-lg"%>
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="bg-light py-5">
    <div class="container"><div class="small text-center text-muted" style="color:#000;"> Copyright © 2020 - CodeQuest Internship Project</div></div>
</footer>
<% end %>

app/views/static_pages/home.html.erb
        
        
        
        <header class="masthead">
            <div class="container h-100">
                <div class="row h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-10 align-self-end">
                        <h1 class="text-uppercase text-white font-weight-bold">We Oragnise Events</h1>
                        <hr class="divider my-4" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 font-weight-light mb-4" id="Event">The Events that are Awesome For Daily stress relief</p>
                        <div class="search">
                          <h3 class="text-white-75 align-left font-weight-light mb-3"><strong id="S-E">You Can Search Events</strong></h3>
                          <form class="form-inline md-form mr-auto mb-4" action="/search">
                            <input class="form-control mr-sm-2" id="input-search" name="title" type="text" placeholder="Search" aria-label="Search">
                            <button class="btn btn-secondary btn-rounded btn-sm my-0" type="submit">Search</button>
                          </form>
                         </div>
                    </div>
                </div>
            </div>
        </header>
        <section class="page-section bg-primary" id="about" style="height:450px;">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h1 class="text-white mt-0">About Us</h1>
                        <hr class="divider light my-4" />
                        <p class="text-white-50 mb-4" id="abt">We to Fun and Awesome Events For Free  so that People can Gain knowledge and Stay updated with What's going on in real World</p>
                    </div>
                </div>
            </div>
        </section>

        <section class="page-section" id="event">
            <div class="container">
                <h2 class="text-center mt-0 event">Current Event Going on!!</h2>
                <hr class="divider my-4" />
                <div class="row m-2">
                    <div class="col-lg-3 col-md-6 text-center">
                      <div class="card card-cascade narrower" id="one">
                        <div class="view view-cascade overlay">
                          <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/Work/4-col/img%20%2821%29.jpg"
                            alt="Math Quiz Image">
                          <a>
                            <div class="mask rgba-white-slight"></div>
                          </a>
                        </div>

                        <div class="card-body card-body-cascade">
                          <h4 class="font-weight-bold card-title">Math Quiz</h4>
                          <p class="card-text">A math quiz that helps you to great in maths and become Gineus.</p>
                          <%= link_to 'Play & Fun','mathQuiz' ,class:"btn btn-primary but_ton"%>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                                               <!-- Card -->
                        <div class="card" id="one">
                          <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/43.jpg" alt="EnglishQuiz Image">
                          <div class="card-body">
                            <h4 class="card-title"><strong><a>English Quiz</a></strong></h4>
                            <p class="card-text">A basic english grammer quiz that helps you to learn English</p>
                          <%= link_to 'Play & Fun','englishQuiz' ,class:"btn btn-primary but_ton"%>
                          </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="card" id="one">
                          <div class="view overlay">
                            <img class="card-img-top" src="https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg"
                              alt="HTML Quiz Image">
                            <a href="#!">
                              <div class="mask rgba-white-slight"></div>
                            </a>
                          </div>
                          <div class="card-body">
                            <h4 class="card-title"><strong>HTML Quiz</strong></h4>
                            <p class="card-text">A Quiz helps you to learn HTML and you become a web Devloper.</p>
                            <%= link_to 'Play & Fun','htmlQuiz' ,class:"btn btn-primary but_ton"%>
                          </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                      <div class="card card-cascade wider h-48" id="one">
                          <div class="view view-cascade overlay">
                            <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/photo6.jpg" alt="GK Quiz Image">
                            <a href="#!">
                              <div class="mask rgba-white-slight"></div>
                            </a>
                          </div>
                          <div class="card-body card-body-cascade text-center">
                            <h4 class="card-title"><strong>GK Quiz</strong></h4>
                            <p class="card-text">A general knowledge Quiz that helps you to build Great IQ. </p>
                          <%= link_to 'Play & Fun','gkQuiz' ,class:"btn btn-primary but_ton"%>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="page-section" id="contact">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="mt-0">Let's Get In Touch!</h2>
                        <hr class="divider my-4" />
                        <p class="text-muted mb-5" style="color:white; font-size:20px;">Any query give us a call or send us an email and we will get back to you as soon as possible!</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0" style="color:#fff;">
                        <i class="fas fa-phone fa-3x mb-3 text-muted" style="color:#fff;"></i>
                        <div>+1 (555) 123-4567</div>
                    </div>
                  <div class="col-lg-4 mr-auto text-center">
                        <i class="fas fa-envelope fa-3x mb-3 text-muted" style="color:#fff;"></i>
                        <a class="d-block" href="mailto:contact@yourwebsite.com" style="color:#fff;">contact@yourwebsite.com</a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container"><div class="small text-center text-muted" style="color:#000;"> Copyright © 2020 - CodeQuest Internship Project</div></div>
        </footer>

app/views/static_pages/htmlQuiz.html.erb
<% if logged_in? %>
<div class="container-fluid" style="margin:0 0 150px 0;">
  <%=link_to 'Back' , 'home',class:"btn btn-secondary btn-lg"%>
</div>
	<%= javascript_pack_tag 'htmlQuiz' %>
<% else %>
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top" style="font-size:32px;">Event Website</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto my-2 my-lg-0">
                <% if logged_in? %>
                      <li class="nav-item">
                        <div class="nav-link">
                        <%= link_to 'Logout', logout_path ,class:"btn btn-warning"%>
                      </li>
                  <% else %>
                      <li class="nav-item">
                        <div class="nav-link">
                        <%= link_to 'Login', login_path ,class:"btn btn-warning"%>
                      </li>
                      <li class="nav-item">
                        <div class="nav-link">
                        <%= link_to 'Sign up', register_path ,class:"btn btn-warning"%>
                      </li>
                  <% end %>
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid" id="error">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template" style="padding:150px 0 0 0;">
                <h1>
                    Oops!</h1>
                <h2>Seems You are not Logged-in</h2>
                <div class="error-details">
                    Sorry, an error has occured, Requested page not found!
                </div>
                <div class="error-actions">
                  <span class="glyphicon glyphicon-home"></span>
                      	 <%= link_to 'Please Login' ,login_path ,class:"btn btn-primary btn-lg"%>
                         <%=link_to 'Back' , 'home',class:"btn btn-info btn-lg"%>
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="bg-light py-5">
    <div class="container"><div class="small text-center text-muted" style="color:#000;"> Copyright © 2020 - CodeQuest Internship Project</div></div>
</footer>
<% end %>

app/views/static_pages/mathQuiz.html.erb
<% if logged_in? %>
<div class="container-fluid" style="margin:0 0 50px 0;">
	<%=link_to 'Back' , 'home',class:"btn btn-secondary btn-lg"%>
</div>
	<%= javascript_pack_tag 'mathQuiz' %>
<% else %>
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="" style="font-size:32px;">Event Website</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto my-2 my-lg-0">
                <% if logged_in? %>
                      <li class="nav-item">
                        <div class="nav-link">
                        <%= link_to 'Logout', logout_path ,class:"btn btn-warning"%>
                      </li>
                  <% else %>
                      <li class="nav-item">
                        <div class="nav-link">
                        <%= link_to 'Login', login_path ,class:"btn btn-warning"%>
                      </li>
                      <li class="nav-item">
                        <div class="nav-link">
                        <%= link_to 'Sign up', register_path ,class:"btn btn-warning"%>
                      </li>
                  <% end %>
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid" id="error">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template" style="padding:150px 0 0 0;">
                <h1>
                    Oops!</h1>
                <h2>Seems You are not Logged-in</h2>
                <div class="error-details">
                    Sorry, an error has occured, Requested page not found!
                </div>
                <div class="error-actions">
                  <span class="glyphicon glyphicon-home"></span>
                      	 <%= link_to 'Please Login' ,login_path ,class:"btn btn-primary btn-lg"%>
                         <%=link_to 'Back' , 'home',class:"btn btn-info btn-lg"%>
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="bg-light py-5">
    <div class="container"><div class="small text-center text-muted" style="color:#000;"> Copyright © 2020 - CodeQuest Internship Project</div></div>
</footer>
<% end %>

app/views/users/register.html.erb
<div class="container">
		<h1 class="text-center">Register for Event</h1>
		<div class="field form-group">
				<%= form_with(model: @user , local: true) do |f| %>
				<%= render 'shared/error_messages' %>

				<%= f.label :name %>
				<%= f.text_field :name ,class:"form-control"%>

				<%= f.label :email %>
				<%= f.text_field :email ,class:"form-control"%>

				<%= f.label :phone_number %>
				<%= f.telephone_field :phone_number, class:"form-control" %>

				<%= f.label :password %>
				<%= f.password_field :password ,class:"form-control"%>

				<%= f.label :password_confirmation %>
				<%= f.password_field :password_confirmation , class:"form-control"%>

				<%= f.submit "Register" , class: "btn btn-primary" %>
				<p>Already Have an Account? <%= link_to "Login" , login_path%></p>
				<% end %>

	</div>

</div>
<footer class="bg-light py-5">
		<div class="container"><div class="small text-center text-muted" style="color:#000;"> Copyright © 2020 - CodeQuest Internship Project</div></div>
</footer>

app/views/users/show.html.erb
<h1>
	Aptitude Quiz
</h1>

<h1>
	coding Quiz
</h1>

<h1>
	verbal Quiz
</h1>